### ISSUE TITLE
running m2 from scratch: CD.6

### ISSUE THREAD

**Issue by jbrannst** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m2-guides#9]
1. install m1,m2
2. follow m2 guides, without doing m1
3. CD section 6 ->
catalog.js already has the baseUrl defined.
It seems the shellscripts to update the monolith also adds the baseUrl correctly, so instructions need to take that into account.

**Comment by danieloh30** [comment]
There's no command to replace the "REPLACEURL" string in the magic script. 
https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m2-labs/blob/master/monolith/scripts/deploy-coolstore.sh

When you take a look at the repo, you can find the "REPLACEURL" string.
https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m2-labs/blob/master/monolith/src/main/webapp/app/services/catalog.js#L18

Can you reproduce your issue? If so, please update the details.

**Comment by jbrannst** [comment]
Makes sense, perhaps someone used my workspace by mistake. Will check when we run this next week!

**Comment by danieloh30** [comment]
Thanks for the updates. I will close this issue now and feel free to reopen or create a new one if you have the same issue.
